name: Auto-merge strategy PRs

on:
  pull_request:
    paths:
      - "strategies/**" # Only run CI if the PR touches files inside /strategies/

jobs:
  run-tournament-and-automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 4: Install any runner dependencies
      - name: Install dependencies
        run: |
          pip install -r runner/requirements.txt

      # Step 5: Run tournament simulation
      - name: Run Tournament Simulation
        run: |
          python runner/tournament_runner.py --strategies ./strategies/

      # Step 6: Auto-merge if all previous steps succeeded
      - name: Auto-merge PR if checks pass
        if: ${{ success() }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
