name: Run Script and Commit Output (Separated Jobs)

on:
  workflow_dispatch:

jobs:
  run_python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run Python script
        run: |
          python3 main.py

      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: script-output
          path: output/

  push_results_to_repo:
    needs: run_python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download output artifact
        uses: actions/download-artifact@v3
        with:
          name: script-output
          path: output/

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add, commit and push output files
        run: |
          git add output/
          git commit -m "Add script output [skip ci]" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
